### ISSUE TITLE
Return undefined for null values?

### ISSUE THREAD

**Issue by ntucakovic** [google/react-schemaorg#12]
![image](https://user-images.githubusercontent.com/6671343/78221413-9e35eb80-74c3-11ea-946f-e5800897256e.png)

What do you think about omitting null values, so those fall in the same bucket as the default switch case? I'd prefer to have a clean output with all valid values, and skipping null entries without having to check in each `<JsonLd>` invocation?

```js
        switch (typeof value) {
            case "object":
                return value; // JSON.stringify will recursively call replacer.
            case "number":
            case "boolean":
            case "bigint":
                return value; // These values are not risky.
            case "string":
                return value.replace(/[&<>'"]/g, replace);
            default: {
                // We shouldn't expect other types.
                isNever(value);
                // JSON.stringify will remove this element.
                return undefined;
            }
        }
```

**Comment by Eyas** [comment]
That sounds like a reasonable change. It would entail returning `undefined` in the `case "object"` case  (since `typeof null === "object"`).

Are you willing to make this PR?
