### ISSUE TITLE
Consider renaming helmetJsonLdProp to a more general name / Support for NextJS

### ISSUE THREAD

**Issue by sebastienlabine** [google/react-schemaorg#23]
Hi, 

I think it would be appropriate to rename the **helmetJsonLdProp** to something more general as it can be with use with other libraries like **next/head** for the **NextJS** Framework. People might not know they can use the function in order to access _innerHTML_, because of the specifity of the name.

Example Usage with NextJS
```html
<script type={jsonLd.type} dangerouslySetInnerHTML={{
      __html: jsonLd.innerHTML
}}></script>
```

I would sugget to change the name to maybe scriptJsonLdProp or headJsonLeadProp.

**Comment by Eyas** [comment]
What you have above is exactly what the main export of shcema-dts does:

```
import { JsonLd } from "react-schemaorg";

<JsonLd<Person> item={{ "@type": "Person", ... }} />
```

is there a reason why this doesn't work with next/head?

**Comment by sebastienlabine** [comment]
In the [documentation of next/head](https://nextjs.org/docs/api-reference/next/head), they are saying:
![image](https://user-images.githubusercontent.com/8888846/87693936-8e34d580-c75b-11ea-8a68-97dd24f3525f.png).

As **JsonLd** wraps the script tag in a higher-level component, in my opinion, it doesn't get picked on by the renderer, hense needing the hack previously mentioned. 

Here's the most basic way you can reproduce in nextjs:

```typescript
import Head from "next/head";
import React from "react";
import { JsonLd } from "react-schemaorg";
export default class ProductHead extends React.Component {
    public render() {
        return (
            <Head>
                    <JsonLd<Product> item={{
                    "@context": "https://schema.org",
                    "@type": "Product",
                    name: "my product name",
                }} />
            </Head>)
      }
}
```

**Comment by Eyas** [comment]
:( I see. I'll look into this.

We might just want to do something neater, e.g.

```
// react-schemaorg
function jsonLdScriptProps<T extends Thing>(item: T) {
  return {
    type: "application/ld+json",
    dangerouslySetInnerHTML: {
      __html: JSON.stringify(/* ... */)
    }
  };
}

// user
export default function MyComponent() {
  return (
    <script {...jsonLdScriptProps<Person>({ /* ... */ })} />
  );
}
```
That feels nicely ergonomic right?

**Comment by sebastienlabine** [comment]
Yes, it looks good! I think it would provide a more flexible api to support more platforms.
