### ISSUE TITLE
Option to not include script tags

### ISSUE THREAD

**Issue by vid** [google/react-schemaorg#3]
There are use cases (mine for example) where I don't want the script tags. In fact I would suggest there should not be any script tags, a library user can always add them.

**Comment by Eyas** [comment]
Can you elaborate what exactly the use case looks like? [schema-dts](https://github.com/google/schema-dts) can be imported directly to allow you to write your own JSON.

> In fact I would suggest there should not be any script tags, a library user can always add them.

That library would be this one (react-schemaorg). I think you will just want to use schema-dts? Unless I'm unclear on the use case here.

**Comment by vid** [comment]
You're right, I didn't realize how minimal this library is. I'll close this issue, thanks.
