### ISSUE TITLE
Escaped characters prevent inclusion of links in FAQ text

### ISSUE THREAD

**Issue by jrood** [google/react-schemaorg#46]
According to [the FAQ schema doc](https://developers.google.com/search/docs/appearance/structured-data/faqpage), the `text` for an `acceptedAnswer` should be able to include link elements. However, the replacer [here](https://github.com/google/react-schemaorg/blob/main/src/json-ld.tsx#L173) escapes angle brackets and double quotes, which should not be escaped if an anchor tag is intended.

**Comment by Eyas** [comment]
I believe this is by design: https://www.w3.org/TR/json-ld11/#restrictions-for-contents-of-json-ld-script-elements

Google's parser should be able to unescape those; JSON-LD inside of a `<script>` tag is by default expected to have some characters escaped.

**Comment by jrood** [comment]
> Google's parser should be able to unescape those

Ah, looks like it does! In that case, I'll close this out.
