### ISSUE TITLE
NewsArticle is not a known valid target type for the itemReviewed attribute

### ISSUE THREAD

**Issue by truongemcom** [google/react-schemaorg#5]
Please guide me how to fix it, thanks a lot.

**Comment by Eyas** [comment]
Hm. itemReviewed should be of type Thing, which should include all know types.

schema-dts controls what version of the schema.org schema you have. I believe 0.4.2 should include the latest types as of today. I'd try to upgrade that

**Comment by Eyas** [comment]
Just checked, since 0.3.1 NewsArticle should work.

**Comment by truongemcom** [comment]
thanks
