### ISSUE TITLE
Breaking potentialAction in Website type

### ISSUE THREAD

**Issue by bsides** [google/react-schemaorg#6]
The schema:

```
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "http://example.com/",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "http://example.com/search?&q={query}",
      "query": "required"
    }
}
```

As specified in https://schema.org/SearchAction doesn't compile. It throws at `potentialAction`, lots of errors in SearchAction, target, etc. Could you point me to the right direction to fix it? I'd gladly help.

Thanks!

EDIT: Fixed removing target, so I believe the error is from schema-dts. Issue opened there https://github.com/google/schema-dts/issues/45

**Comment by Eyas** [comment]
The workaround is:

```
      "target": {
        "@type": "EntryPoint",
        "urlTemplate": "http://example.com/search?&q={query}"
      },
```

instead of just string. will fix in schema-dts.
